version: "3"
services:
    web:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - "postgis"
        logvolume01: {}
    postgis:
        image: postgis/postgis:12-3.0-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
