version: "3"
services:
    web:
        build: .
        # restart: always
        ports:
            - "3000:3000"
        depends_on:
            - "postgis"
        command: ['./wait-for-it.sh', 'postgis:5432', 'node', 'db.js']
        # logvolume01: {}
        environment:
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
    postgis:
        image: postgis/postgis:11-3.0-alpine
        # restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
