version: "3"
services:
    web:
        image: delongw/tortuous:${TAG}
        restart: always
        ports: 
            - "3000:3000"
        depends_on:
            - "postgis"
        env_file: postgres.env
    postgis:
        image: postgis/postgis:11-3.0-alpine
        restart: always
        ports: 
            - "5432:5432"
        env_file: postgres.env
